{% set name = "yamale" %}
{% set version = "3.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bec53aa08e29c26a9a47c0f5d5cb5632e7ac8aff619a4727acfe490042c83a5f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - yamale = yamale.command_line:main

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6
    - pyyaml

test:
  imports:
    - yamale
  commands:
    - yamale -h

about:
  home: https://github.com/23andMe/Yamale
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A schema and validator for YAML.
  description: |
    A schema and validator for YAML.
  doc_url: https://github.com/23andMe/Yamale
  dev_url: https://github.com/23andMe/Yamale

extra:
  recipe-maintainers:
    - adament
