{% set name = "yamale" %}
{% set version = "5.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 19bbe713d588f07177bc519a46070c0793ed126ea37f425a76055b99703f835a

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - yamale = yamale.command_line:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pyyaml

test:
  requires:
    - python {{ python_min }}
  imports:
    - yamale
  commands:
    - yamale -h

about:
  home: https://github.com/23andMe/Yamale
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A schema and validator for YAML.
  description: |
    A schema and validator for YAML.
  doc_url: https://github.com/23andMe/Yamale
  dev_url: https://github.com/23andMe/Yamale

extra:
  recipe-maintainers:
    - adament
